namespace EventHorizon.Blazor.TypeScript.Interop.Generator.Phaser.ConsoleApp
{
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.IO;
    using EventHorizon.Blazor.TypeScript.Interop.Generator.Formatter;
    using EventHorizon.Blazor.TypeScript.Interop.Generator.Logging;

    using ServerGenerator = Blazor.Interop.Generator.GenerateInteropSource;
    using ServerProjectWriter = Blazor.Interop.Generator.Writers.Project.ServerProjectWriter;
    using WasmGenerator = GenerateSource;
    using WasmProjectWriter = Writers.Project.ProjectWriter;

    public class Program
    {
        static void Main(string[] args)
        {
            //Run(AstParser.Model.ASTParserType.NodeJS, true); //  75084ms/71877ms to generate.
            Run( AstParser.Model.ASTParserType.Sdcb, true, "EventHorizon.Blazor.Phaser.WASM" ); //  22027ms/19835ms/18236ms to generate.

            //    Run( AstParser.Model.ASTParserType.Sdcb, false, "EventHorizon.Blazor.BabylonJS.Server" );

        }

        static void Run( AstParser.Model.ASTParserType type, bool useWasm, string projectAssembly )
        {
            var stopwatch = Stopwatch.StartNew();
            //var projectAssembly = "EventHorizon.Blazor.BabylonJS.WASM";
            var projectGenerationLocation = Path.Combine( "..", "_generated" );
            var sourceDirectory = Path.Combine( ".", "SourceFiles" );
            var textFormatter = new NoFormattingTextFormatter();

            var sourceFiles = new List<string>
            {
                "matter.d.ts",
          /*     "phaser.d.ts",
                "spine.d.ts",
                "spine-canvas.d.ts",
                "SpineContainer.d.ts",
                "SpineFile.d.ts",
                "SpineGameObject.d.ts",
                "SpinePlugin.d.ts",
                "spine-webgl.d.ts",*/
            };

            var generationList = new List<string>
            {
                // matters file
                // interfaces
                "IChamfer",
                "IChamferableBodyDefinition",
                "IBodyDefinition",
                "IBodyRenderOptions",
                "IBodyRenderOptionsSprite",
                "IBound",
                "ICompositeDefinition",
                "IConstraintDefinition",
                "IConstraintRenderDefinition",
                "IEngineDefinition",
                "IEngineTimingOptions",
                "IMouseConstraintDefinition",
                "IGridDefinition",
                "IPair",
                "ICollisionData",
                "ICollisionPair",
                "ICollisionFilter",
                "IRunnerOptions",
                "IWorldDefinition",
                "Gravity",
                "IEvent",
                "IEventComposite",
                "IEventTimestamped",
                "IEventCollision",

                // types
                "CompositeType",
                "ConstraintType",
                "BodyType",
                "Dependency",

                // classes
                "Axes",
                "AxesFactory",
                "Bodies",
                "BodiesFactory",
                "Body",
                "BodyFactory",
                "Bounds",
                "BoundsFactory",
                "Composite",
                "CompositeFactory",
                "Composites",
                "CompositesFactory",
                "Constraint",
                "ConstraintFactory",
                "Engine",
                "Grid",
                "GridFactory",
                "MouseConstraint",
                "Pairs",
                "PairsFactory",
                "Pair",
                "PairFactory",
                "Detector",
                "DetectorFactory",
                "Resolver",
                "ResolverFactory",
                "SAT",
                "SATFactory",
                "Query",
                "QueryFactory",
                "Runner",
                "Sleeping",
                "SleepingFactory",
                "Svg",
                "SvgFactory",
                "Vector",
                "VectorFactory",
                "Vertices",
                "VerticesFactory",
                "World",
                "Events",
                "Plugin",
/*
                // phaser file
                // interface
                "Alpha ",
                "AlphaSingle ",
                "BlendMode ",
                "ComputedSize ",
                "Crop ",
                "Depth ",
                "Flip ",
                "GetBounds ",
                "Mask ",
                "Origin ",
                "PathFollower ",
                "Pipeline ",
                "ScrollFactor ",
                "Size ",
                "Texture ",
                "TextureCrop ",
                "Tint ",
                "ToJSON ",
                "Transform ",
                "Visible ",
                "Acceleration ",
                "Angular ",
                "Bounce ",
                "Debug ",
                "Drag ",
                "Enable ",
                "Friction ",
                "Gravity ",
                "Immovable ",
                "Mass ",
                "OverlapCirc ",
                "OverlapRect ",
                "Pushable ",
                "Size ",
                "Velocity ",
                "Bounce ",
                "Collision ",
                "Force ",
                "Friction ",
                "Gravity ",
                "Mass ",
                "Sensor ",
                "SetBody ",
                "Sleep ",
                "Static ",
                "Transform ",
                "Velocity ",
                
                // types
                "CameraRotateCallback",
                "DataEachCallback",
                "ContentLoadedCallback",
                "CreateCallback",
                "EachContainerCallback",
                "LightForEach",
                "TextStyleWordWrapCallback",
                "CenterFunction",
                "ArcadePhysicsCallback",
                "WebGLContextCallback",
                "EachListCallback",
                "EachMapCallback",
                "EachSetCallback",
                "EachTextureCallback",
                "FindTileCallback",
                "EachTileCallback",
                "TilemapFilterCallback",
                "TilemapFindCallback",
                "AdInstance",
                "ContextFilter",
                "ChooseContextConfig",
                "LeaderboardScore",
                "Product",
                "Purchase",
                "integer",

                // classes
                "Animation",
                "AnimationFrame",
                "AnimationManager",
                "AnimationState",
                "BaseCache",
                "CacheManager",
                "BaseCamera",
                "Camera",
                "CameraManager",
                "Fade",
                "Flash",
                "Pan",
                "RotateTo",
                "Shake",
                "Zoom",
                "FixedKeyControl",
                "SmoothedKeyControl",
                "Game",
                "Config",
                "TimeStep",
                "CubicBezier",
                "Curve",
                "Ellipse",
                "Line",
                "MoveTo",
                "Path",
                "QuadraticBezier",
                "Spline",
                "DataManager",
                "DataManagerPlugin",
                "Color",
                "ColorMatrix",
                "BitmapMask",
                "GeometryMask",
                "RGB",
                "BaseShader",
                "RequestAnimationFrame",
                "EventEmitter",
                "DynamicBitmapText",
                "BitmapText",
                "Blitter",
                "Bob",
                "TransformMatrix",
                "Container",
                "DisplayList",
                "DOMElement",
                "Extern",
                "GameObject",
                "GameObjectCreator",
                "GameObjectFactory",
                "Graphics",
                "Group",
                "Image",
                "Layer",
                "Light",
                "LightsManager",
                "LightsPlugin",
                "Mesh",
                "EmitterOp",
                "GravityWell",
                "Particle",
                "ParticleEmitter",
                "ParticleEmitterManager",
                "DeathZone",
                "EdgeZone",
                "RandomZone",
                "PathFollower",
                "PointLight",
                "RenderTexture",
                "Rope",
                "Shader",
                "Arc",
                "Curve",
                "Ellipse",
                "Grid",
                "IsoBox",
                "IsoTriangle",
                "Line",
                "Polygon",
                "Rectangle",
                "Shape",
                "Star",
                "Triangle",
                "Sprite",
                "Text",
                "TextStyle",
                "TileSprite",
                "UpdateList",
                "Video",
                "Zone",
                "Circle",
                "Ellipse",
                "Line",
                "Face",
                "Vertex",
                "Point",
                "Polygon",
                "Rectangle",
                "Triangle",
                "Axis",
                "Button",
                "Gamepad",
                "GamepadPlugin",
                "InputManager",
                "InputPlugin",
                "KeyCombo",
                "KeyboardManager",
                "KeyboardPlugin",
                "Key",
                "MouseManager",
                "Pointer",
                "TouchManager",
                "File",
                "AnimationJSONFile",
                "AsepriteFile",
                "AtlasJSONFile",
                "AtlasXMLFile",
                "AudioFile",
                "AudioSpriteFile",
                "BinaryFile",
                "BitmapFontFile",
                "CSSFile",
                "GLSLFile",
                "HTML5AudioFile",
                "HTMLFile",
                "HTMLTextureFile",
                "ImageFile",
                "JSONFile",
                "MultiAtlasFile",
                "MultiScriptFile",
                "OBJFile",
                "PackFile",
                "PluginFile",
                "SceneFile",
                "ScenePluginFile",
                "ScriptFile",
                "SpriteSheetFile",
                "SVGFile",
                "TextFile",
                "TilemapCSVFile",
                "TilemapImpactFile",
                "TilemapJSONFile",
                "UnityAtlasFile",
                "VideoFile",
                "XMLFile",
                "LoaderPlugin",
                "MultiFile",
                "Euler",
                "Matrix3",
                "Matrix4",
                "Quaternion",
                "RandomDataGenerator",
                "Vector2",
                "Vector3",
                "Vector4",
                "Image",
                "ArcadePhysics",
                "Sprite",
                "Body",
                "Collider",
                "Factory",
                "Group",
                "StaticBody",
                "StaticGroup",
                "World",
                "BodyBounds",
                "Factory",
                "Image",
                "MatterPhysics",
                "Sprite",
                "TileBody",
                "PointerConstraint",
                "World",
                "BasePlugin",
                "PluginManager",
                "ScenePlugin",
                "CanvasRenderer",
                "PipelineManager",
                "BitmapMaskPipeline",
                "GraphicsPipeline",
                "LightPipeline",
                "MultiPipeline",
                "PointLightPipeline",
                "PostFXPipeline",
                "RopePipeline",
                "SinglePipeline",
                "UtilityPipeline",
                "RenderTarget",
                "WebGLPipeline",
                "WebGLRenderer",
                "WebGLShader",
                "ScaleManager",
                "SceneManager",
                "ScenePlugin",
                "Systems",
                "Scene",
                "BaseSound",
                "BaseSoundManager",
                "HTML5AudioSound",
                "HTML5AudioSoundManager",
                "NoAudioSound",
                "NoAudioSoundManager",
                "WebAudioSound",
                "WebAudioSoundManager",
                "List",
                "Map",
                "ProcessQueue",
                "RTree",
                "Set",
                "Size",
                "CanvasTexture",
                "Frame",
                "Texture",
                "TextureManager",
                "TextureSource",
                "ImageCollection",
                "LayerData",
                "MapData",
                "ObjectLayer",
                "Tile",
                "Tilemap",
                "TilemapLayer",
                "Tileset",
                "Clock",
                "TimerEvent",
                "Timeline",
                "Tween",
                "TweenManager",
                "FacebookInstantGamesPlugin",
                "FacebookInstantGamesLeaderboard",


                // spine file
                // interfaces
                "Timeline",
                "AnimationStateListener2",
                "Updatable",
                "Map",
                "Disposable",
                "Restorable",
                "ArrayLike",
                "VertexEffect",
                "Math",
                "AttachmentLoader",

                // classes
                "Animation",
                "CurveTimeline",
                "RotateTimeline",
                "TranslateTimeline",
                "ScaleTimeline",
                "ShearTimeline",
                "ColorTimeline",
                "TwoColorTimeline",
                "AttachmentTimeline",
                "DeformTimeline",
                "EventTimeline",
                "DrawOrderTimeline",
                "IkConstraintTimeline",
                "TransformConstraintTimeline",
                "PathConstraintPositionTimeline",
                "PathConstraintSpacingTimeline",
                "PathConstraintMixTimeline",
                "AnimationState",
                "TrackEntry",
                "EventQueue",
                "AnimationStateAdapter2",
                "AnimationStateData",
                "AssetManager",
                "AtlasAttachmentLoader",
                "Bone",
                "BoneData",
                "ConstraintData",
                "Event",
                "EventData",
                "IkConstraint",
                "IkConstraintData",
                "PathConstraint",
                "PathConstraintData",
                "SharedAssetManager",
                "Skeleton",
                "SkeletonBinary",
                "SkeletonBounds",
                "SkeletonClipping",
                "SkeletonData",
                "SkeletonJson",
                "SkinEntry",
                "Skin",
                "Slot",
                "SlotData",
                "Texture",
                "TextureRegion",
                "FakeTexture",
                "TextureAtlas",
                "TextureAtlasPage",
                "TextureAtlasRegion",
                "TransformConstraint",
                "TransformConstraintData",
                "Triangulator",
                "IntSet",
                "Color",
                "MathUtils",
                "Interpolation",
                "Pow",
                "PowOut",
                "Utils",
                "DebugUtils",
                "EventTimeline",
                "Pool",
                "Vector2",
                "TimeKeeper",
                "WindowedMean",
                "Attachment",
                "VertexAttachment",
                "BoundingBoxAttachment",
                "ClippingAttachment",
                "MeshAttachment",
                "PathAttachment",
                "PointAttachment",
                "RegionAttachment",
                "JitterEffect",
                "SwirlEffect",
                "AssetManager",
                "CanvasTexture",
                "SkeletonRenderer",
                "AssetManager",
                "OrthoCamera",
                "GLTexture",
                "Matrix4",
                "Mesh",
                "VertexAttribute",
                "Position2Attribute",
                "Position3Attribute",
                "TexCoordAttribute",
                "ColorAttribute",
                "Color2Attribute",
                "PolygonBatcher",
                "SceneRenderer",
                "Shader",
                "ShapeRenderer",
                "SkeletonDebugRenderer",
                "SkeletonRenderer",
                "Vector3",
                "ManagedWebGLRenderingContext",
                "WebGLBlendModeConverter",


                // spine-canvas
                // interfaces
                "Timeline",
                "AnimationStateListener2",
                "Updatable",
                "Map",
                "Disposable",
                "Restorable",
                "ArrayLike",
                "VertexEffect",
                "Math",
                "AttachmentLoader",

                // classes
                "Animation",
                "CurveTimeline",
                "RotateTimeline",
                "TranslateTimeline",
                "ScaleTimeline",
                "ShearTimeline",
                "ColorTimeline",
                "TwoColorTimeline",
                "AttachmentTimeline",
                "DeformTimeline",
                "EventTimeline",
                "DrawOrderTimeline",
                "IkConstraintTimeline",
                "TransformConstraintTimeline",
                "PathConstraintPositionTimeline",
                "PathConstraintSpacingTimeline",
                "PathConstraintMixTimeline",
                "AnimationState",
                "TrackEntry",
                "EventQueue",
                "AnimationStateAdapter2",
                "AnimationStateData",
                "AssetManager",
                "AtlasAttachmentLoader",
                "Bone",
                "BoneData",
                "ConstraintData",
                "Event",
                "EventData",
                "IkConstraint",
                "IkConstraintData",
                "PathConstraint",
                "PathConstraintData",
                "SharedAssetManager",
                "Skeleton",
                "SkeletonBinary",
                "SkeletonBounds",
                "SkeletonClipping",
                "SkeletonData",
                "SkeletonJson",
                "SkinEntry",
                "Skin",
                "Slot",
                "SlotData",
                "Texture",
                "TextureRegion",
                "FakeTexture",
                "TextureAtlas",
                "TextureAtlasPage",
                "TextureAtlasRegion",
                "TransformConstraint",
                "TransformConstraintData",
                "Triangulator",
                "IntSet",
                "Color",
                "MathUtils",
                "Interpolation",
                "Pow",
                "PowOut",
                "Utils",
                "DebugUtils",
                "Pool",
                "Vector2",
                "TimeKeeper",
                "WindowedMean",
                "Attachment",
                "VertexAttachment",
                "BoundingBoxAttachment",
                "ClippingAttachment",
                "MeshAttachment",
                "PathAttachment",
                "PointAttachment",
                "RegionAttachment",
                "JitterEffect",
                "SwirlEffect",
                "AssetManager",
                "CanvasTexture",
                "SkeletonRenderer",


                // SpineContainer
                // interface
                "SpineContainerConfig",
                
                // class
                "SpineContainerConfig",
                "SpineContainer",


                // SpineFile
                // interface
                "SpineFileConfig",

                // class
                "SpineFile",


                // SpineGameObject
                // interface
                "SpineGameObjectConfig",
                
                // class
                "SpineGameObject",
                

                // SpinePlugin
                // interface
                "LoaderPlugin",
                "GameObjectFactory",
                "GameObjectCreator",

                // class
                "SpinePlugin",
                

                // spine-webgl
                // interfaces
                "Timeline",
                "AnimationStateListener2",
                "Updatable",
                "Map",
                "Disposable",
                "Restorable",
                "ArrayLike",
                "VertexEffect",
                "Math",
                "AttachmentLoader",

                // classes
                "Animation",
                "CurveTimeline",
                "RotateTimeline",
                "TranslateTimeline",
                "ScaleTimeline",
                "ShearTimeline",
                "ColorTimeline",
                "TwoColorTimeline",
                "AttachmentTimeline",
                "DeformTimeline",
                "EventTimeline",
                "DrawOrderTimeline",
                "IkConstraintTimeline",
                "TransformConstraintTimeline",
                "PathConstraintPositionTimeline",
                "PathConstraintSpacingTimeline",
                "PathConstraintMixTimeline",
                "AnimationState",
                "TrackEntry",
                "EventQueue",
                "AnimationStateAdapter2",
                "AnimationStateData",
                "AssetManager",
                "AtlasAttachmentLoader",
                "Bone",
                "BoneData",
                "ConstraintData",
                "Event",
                "EventData",
                "IkConstraint",
                "IkConstraintData",
                "PathConstraint",
                "PathConstraintData",
                "SharedAssetManager",
                "Skeleton",
                "SkeletonBinary",
                "SkeletonBounds",
                "SkeletonClipping",
                "SkeletonData",
                "SkeletonJson",
                "SkinEntry",
                "Skin",
                "Slot",
                "SlotData",
                "Texture",
                "TextureRegion",
                "FakeTexture",
                "TextureAtlas",
                "TextureAtlasPage",
                "TextureAtlasRegion",
                "TransformConstraint",
                "TransformConstraintData",
                "Triangulator",
                "IntSet",
                "Color",
                "MathUtils",
                "Interpolation",
                "Pow",
                "PowOut",
                "Utils",
                "DebugUtils",
                "Pool",
                "Vector2",
                "TimeKeeper",
                "WindowedMean",
                "Attachment",
                "VertexAttachment",
                "BoundingBoxAttachment",
                "ClippingAttachment",
                "MeshAttachment",
                "PathAttachment",
                "PointAttachment",
                "RegionAttachment",
                "JitterEffect",
                "SwirlEffect",
                "AssetManager",
                "OrthoCamera",
                "GLTexture",
                "Matrix4",
                "Mesh",
                "VertexAttribute",
                "Position2Attribute",
                "Position3Attribute",
                "TexCoordAttribute",
                "ColorAttribute",
                "Color2Attribute",
                "PolygonBatcher",
                "SceneRenderer",
                "Shader",
                "ShapeRenderer",
                "SkeletonDebugRenderer",
                "SkeletonRenderer",
                "Vector3",
                "ManagedWebGLRenderingContext",
                "WebGLBlendModeConverter",
*/
            };

            // Remove any already Generated Source.
            if (Directory.Exists(Path.Combine( projectGenerationLocation, projectAssembly )))
            {
                Directory.Delete( Path.Combine( projectGenerationLocation, projectAssembly ), true );
            }

            GlobalLogger.Info("Removed Generation Directory");

            if (useWasm)
            {
                GlobalLogger.Info("Running Wasm Generator");
                var writer = new WasmProjectWriter( projectGenerationLocation, projectAssembly );
                
                new WasmGenerator().Run(
                    projectAssembly,
                    sourceDirectory,
                    sourceFiles,
                    generationList,
                    writer,
                    textFormatter,
                    new Dictionary<string, string>
                    {
                        { "Phaser.PointerInfoBase | type", "int" }
                    },
                    type
                );
            }
            else
            {
                GlobalLogger.Info("Running Server Generator");
                var writer = new ServerProjectWriter( projectGenerationLocation, projectAssembly );
                
                new ServerGenerator().Run(
                    projectAssembly,
                    sourceDirectory,
                    sourceFiles,
                    generationList,
                    writer,
                    textFormatter,
                    new Dictionary<string, string>
                    {
                        { "Phaser.PointerInfoBase | type", "int" }
                    },
                    type
                );
            }

            stopwatch.Stop();
            GlobalLogger.Info("Removed Generation Directory");
            GlobalLogger.Info($"Took {stopwatch.ElapsedMilliseconds}ms to generate.");
        }
    }
}
